#! /bin/bash

qmake-qt4 ModelQT_GUI.pro -r -spec linux-g++
make -w
./ModelQT_GUI&
make clean

#need to change the makefile to include PNGwriter:
# PNGWRITE = -I/usr/local/lib -L/usr/local/include -lpng -lpngwriter -lz -lfreetype -DNO_FREETYPE
#then add ${PNGWRITE) to the end of all of the files in the "######### compile" section.